image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          # install deps
          - apt-get update && apt-get install -y jq
          - npm install
          # run tests
          - npm run lint
          - npm run test:unit:coverage
          - npm run test:functional:cli minimal $TEST_SFCC_CLIENT_ID $TEST_SFCC_CLIENT_SECRET $TEST_SFCC_INSTANCE $TEST_AM_USER $TEST_AM_USER_PW
  custom:
    regression:
      - step:
          caches:
            - node
          script:
            # install deps
            - apt-get update && apt-get install -y jq
            - npm install
            # run tests
            - npm run lint
            - npm run test:unit:coverage
            - npm run test:functional:cli full $TEST_SFCC_CLIENT_ID $TEST_SFCC_CLIENT_SECRET $TEST_SFCC_INSTANCE
            # dist and upload latest binaries into downloads section
            - npm run dist
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/sfcc-ci-linux"
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/sfcc-ci-macos"
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/sfcc-ci-win.exe"